version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    container_name: khadamati-ai_nginx
  
  app:
    image: thecodingmachine/php:7.2-v1-apache-node8
    volumes:
      - ./:/var/www/html:rw
    environment:
      - VIRTUAL_HOST=app.khadamati-ai.dev
      - PHP_INI_ERROR_REPORTING=E_ALL & ~E_USER_DEPRECATED
      - PHP_EXTENSION_XDEBUG=1
    env_file:
      - .env
    container_name: khadamati-ai_app
    links:
      - "phpmyadmin:khadamati-ai_phpmyadmin"
  mysql:
    image: mysql:5.7
    env_file:
      - .env
    volumes:
      - ./.docker/data/mysql/:/var/lib/mysql
      - ./.docker/logs/mysql/:/var/log/mysql
    container_name: khadamati-ai_mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      -  8080:8080
    env_file:
      - .env
    environment:
      PMA_HOST: mysql
      VIRTUAL_HOST: phpmyadmin.khadamati-ai.dev   
    container_name: khadamati-ai_phpmyadmin

  postgres:
    image: postgres
  django:
    build: app-front-django/
    command: python3 app-front-django/manage.py runserver 0.0.0.0:8010
    volumes:
      - .:/code
    ports:
      - "8010:8010"
    depends_on:
      - postgres