# Generated by Django 2.0.4 on 2018-04-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('dialect', models.CharField(max_length=50)),
                ('key', models.IntegerField()),
                ('translated', models.BooleanField(default=False)),
            ],
        ),
    ]
