# Generated by Django 2.0.4 on 2018-04-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionnary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='key',
            field=models.IntegerField(unique=True),
        ),
    ]
