# Generated by Django 2.0.4 on 2018-04-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionnary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='translated',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
