# Generated by Django 2.0.4 on 2018-04-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=200)),
                ('dialect', models.CharField(max_length=50)),
                ('sentiment', models.CharField(max_length=10)),
            ],
        ),
    ]
